encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  toc_levels: 2..3

permalink: /:year/:month/:title.html

sass:
  sass_dir: /src/stylesheet/scss
  style: compressed

base_url: https://wy-ei.github.io/notebook
# base_url: ''

images: https://wy-ei.github.io/notebook/images
# images: /images


title: WangYu's Notes
slogan: 好记性不如烂笔头
domain: wy-ei.github.io

excerpt_separator: "<!--more-->"

author:
  name: wangyu
  email: wangyu_it@yeah.net
  github: wy-ei
